server:
  port: 80

eureka:
  client:
    register-with-eureka: true    #注册进注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版

#设置Feign客户端的超时时间(OpenFeign默认支持Ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
  ConnectTimeout: 5000   #改成5s
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000     #改成5秒
logging:
  level:
    #Feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug

