server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的 rabbitmq 的服务信息
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbit:
                host: 172.16.208.147
                port: 5672
                username: hedon
                password: hedon
                virtual-host: /hedon
      bindings:   # 服务的整合处理
        input:   #消费者要用input
          destination: studyExchange # 表示要使用的 Exchange ，和生产者一样
          content-type: application/json
          binder: defaultRabbit
  #配置 rabbitmq
  rabbitmq:
    host: 172.16.208.147
    port: 5672
    username: hedon
    password: hedon
    virtual-host: /hedon
#服务注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版

management:
  endpoints:
    web:
      exposure:
        include: "*"

